# Generated by Django 4.1 on 2022-08-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
                ('release_date', models.DateField()),
                ('lte_exists', models.CharField(max_length=20)),
                ('slug', models.SlugField(max_length=200)),
            ],
        ),
    ]
